# golangci-lint configuration v2
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  # Disable all default linters
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    govet:
      disable:
        - shadow
    
    staticcheck:
      checks:
        - "SA*"
        - "-SA9003"

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
