# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - exportloopref

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/ned1313/tf-mirror
  
  misspell:
    locale: US
  
  gosec:
    excludes:
      - G104 # Audit errors not checked
      - G304 # File path provided as taint input

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - noctx
    
    # Exclude known issues in generated files
    - path: internal/database/models\.go
      linters:
        - unused
  
  max-issues-per-linter: 0
  max-same-issues: 0
